
---
title: "Class notes 9.10"
format: html
embed-resources: true
---

```{r}
#| message: false
#| label: setup

library(tidyverse)
```

## Faceting

Let's break down `penguins` bill length and depth by species. 

```{r}
ggplot(penguins, aes(x = bill_len,
                     y = bill_dep)) +
  geom_point() +
  facet_wrap(~species)
```

```{r}
ggplot(penguins, aes(x = bill_len,
                     y = bill_dep)) +
  geom_point() +
  facet_wrap(~species,
             ncol = 1)
```

Let's make this pretty.

```{r}
#| warning: false

ggplot(penguins, aes(x = bill_len,
                     y = bill_dep,
                     color = species)) +
  geom_point() +
  labs(x = "Bill length (mm)",
       y = "Bill depth (mm)",
       color = "Species",
       title = "Penguin bills") +
  facet_wrap(~species,
             ncol = 1) +
  scale_color_brewer(palette = "Dark2") +
  theme_minimal()
```

Let's do one more plot using `sex`. For illustration only; this isn't a great plot.

```{r}
ggplot(penguins, aes(x = bill_len,
                     y = bill_dep,
                     color = sex)) + 
  geom_point() +
  facet_wrap(~species) + 
  scale_color_brewer(palette = "Dark2") +
  theme_minimal()
```
